### ISSUE TITLE
Collision with item not in list

### ISSUE THREAD

**Issue by Chrismarsh** [rizkg/BooPHF#12]
Using the super-fast wyhash hash function (https://github.com/wangyi-fudan/wyhash), I'm seeing a collision between two integers, one of which is not in the list.

Specifically:
- I compile-time hash strings to uint64_h using xxh64.
- I then use these hashes to build up bbhash which has been created to use the wyhash function
- If I query a specific hash that isn't in the table, it doesn't properly return UINT max

I've attached a minimum working example to this post. My output is as follows, which I hope helps illustrate the problem further. 

``` 
$ g++ main.cpp -o out -lpthread && ./out

area = 9853546745770798894
Ninja21_V = 10499620994759670644
HelloWorld = 990340755478284348

wyand hash of area = 1514463996213185106
wyand hash of Ninja21_V = 135295144726059243

Looking up area which is not in the map: 0
Looking up Ninja21_V which is in the map: 0
Looking up HelloWorld which is not in the map: 18446744073709551615
```

[bbhash-collision.zip](https://github.com/rizkg/BBHash/files/3023619/bbhash-collision.zip)

**Comment by rob-p** [comment]
Hi @Chrismarsh,

  Please note that, under the definition of minimal perfect hash functions (and all practical implementations of which I am aware), some element e that was _not in the keyset_ at the time of construction will have a non-trivial probability of colliding with an indexed element.  That is, for an element outside of the indexed keyset, you cannot make any assumption on how it will be mapped by the MPHF --- it could return an invalid index, or it could return a number in [0,N) and collide with some element that was indexed in the keyset.  So, I don't think this unexpected behavior.

--Rob

**Comment by Chrismarsh** [comment]
Hi @rob-p,

Interesting, I didn't realize that. I had taken this check
https://github.com/rizkg/BBHash/blob/master/BooPHF.h#L986
to be explicitly checking that condition.

99% of my keys I look up I can guarantee will be in the map, but once and a while I do need to check. I will add an explicit check that the item returned == the item requested. It will add a bit of overhead, but I don't see any other way. Unless you have another recommendation?

**Comment by rob-p** [comment]
Hi @Chrismarsh,

  I believe that the purpose of that line is to ensure that _known_ "alien" elements are assigned a value of `ULLONG_MAX`, as they would otherwise be assigned some potentially random number.  However, if an element from outside the keyset collides, that simply means they are indistinguishable under the constructed hash (which is different from them having identical hash values in the basic top-level hash function you are using).

  What you propose is the standard way to deal with this issue of MPHFs.  That is, check that the item you get back is the same as the item you searched for to avoid these "false positives".  If you're already storing the elements themselves in the hash table (array) anyway, this will hopefully be only a little more work and it will guarantee you don't have any collisions.

**Comment by Chrismarsh** [comment]
Perfect. Thanks very much for the help and my apologies about this!

Side note: Awesome library, super helpful for my work.

**Comment by rizkg** [comment]
Yes, Rob is totally correct.
When querying an element that was not in the original keyset used in the construction, there is no guarantee. For some outside elements we can sometimes tell that they are outsiders, and in that case return `ULLONG_MAX`. I will add an explanation in the readme.
And thanks for the kind words :)
