### ISSUE TITLE
non-de-duplicated input

### ISSUE THREAD

**Issue by ekg** [rizkg/BooPHF#14]
I'm curious what drawbacks there are when not removing duplicates from BBhash's input.

I could save quite a bit of compute effort in my case if I can provide BBhash with duplicate keys, but I'd prefer not to do this if there are serious issues that might result.

**Comment by rizkg** [comment]
Hi,
If you have only a few duplicate keys in the input then the effect will only be a marginal increase in construction time and memory usage. If you measured that overall you save time by not de-duplicating then you are good to go.
More precisely, each key that appears more than once in the input will require approx 42 B of memory, instead of a few bits. 
So one key that appears a million time would be ok.
The degenerate case would be if all your keys appear twice. It will not bug or crash, but would lead to a very high memory usage, and would not be efficient compared to another structure such as a simple hashtable .

**Comment by rchikhi** [comment]
So 42 bytes per duplicated key, no matter how many times it has been duplicated, right?
